FROM node:21.4.0-bookworm

WORKDIR /app

COPY ./y-websocket-server/package.json /app
COPY ./y-websocket-server/package-lock.json /app

RUN npm ci --force # we don't love --force but i think react canary ends up making us need it

COPY ./y-websocket-server /app

COPY ./prisma /app/prisma

ENV NODE_ENV=production

ENV PRISMA_OUTPUT="/app/node_modules/.prisma/client"
RUN npx prisma generate

RUN npm run build

ENTRYPOINT ["node", "dist/server.js"]

